export const Theme =  {
    colors: {
        color1: '#040404',
        color2: 'blue',
        color3: 'purple',
    },
    items: {
        skins: [
            { id: 0, item:'skins/skin.png', },
            { id: 1, item:'/skins/skin_01.png', },
            { id: 2, item:'assets/skins/skin_02.png', },
            { id: 3, item:'images/skins/skin_03.png', },
            { id: 4, item:'/imagens/skins/skin_04.png', },
            { id: 5, item:'assets/skins/skin_05.png', },
            { id: 6, item:'assets/skins/skin_06.png',
        }
        ],
        clothes: [
            { id: 0, item: 'src/assets/clothes/cloth_01.png', },
            { id: 1, item: 'src/assets/clothes/cloth_02.png', },
            { id: 2, item: 'src/assets/clothes/cloth_03.png', },
            { id: 3, item: 'src/assets/clothes/cloth_04.png', },
            { id: 4, item: 'src/assets/clothes/cloth_05.png', },
            { id: 5, item: 'src/assets/clothes/cloth_06.png', },
            { id: 6, item: 'src/assets/clothes/cloth_07.png', },
            { id: 7, item: 'src/assets/clothes/cloth_08.png', },
            { id: 8, item: 'src/assets/clothes/cloth_09.png', },
            { id: 9, item: 'src/assets/clothes/cloth_10.png', },
            { id: 10, item: 'src/assets/clothes/cloth_11.png', },
            { id: 11, item: 'src/assets/clothes/cloth_12.png', },
            { id: 12, item: 'src/assets/clothes/cloth_13.png', },
            { id: 13, item: 'src/assets/clothes/cloth_14.png', }
        ],
        mounth : [
            { id: 0, item: 'src/assets/mounth/mounth_01.png' },
            { id: 1, item: 'src/assets/mounth/mounth_02.png' },
            { id: 2, item: 'src/assets/mounth/mounth_03.png' },
            { id: 3, item: 'src/assets/mounth/mounth_04.png' },
            { id: 4, item: 'src/assets/mounth/mounth_05.png' },
            { id: 5, item: 'src/assets/mounth/mounth_06.png' },
            { id: 6, item: 'src/assets/mounth/mounth_07.png' },
            { id: 7, item: 'src/assets/mounth/mounth_08.png' },
        ],
        eyes: [
            { id: 0, item: 'src/assets/eyes/eyes_01.png' },
            { id: 1, item: 'src/assets/eyes/eyes_02.png' },
            { id: 2, item: 'src/assets/eyes/eyes_03.png' },
            { id: 3, item: 'src/assets/eyes/eyes_04.png' },
            { id: 4, item: 'src/assets/eyes/eyes_05.png' },
            { id: 5, item: 'src/assets/eyes/eyes_06.png' },
            { id: 6, item: 'src/assets/eyes/eyes_07.png' },
        ],
        head: [
            { id: 0, item: 'src/assets/head/head_01.png' },
            { id: 1, item: 'src/assets/head/head_02.png' },
            { id: 2, item: 'src/assets/head/head_03.png' },
            { id: 3, item: 'src/assets/head/head_04.png' },
            { id: 4, item: 'src/assets/head/head_05.png' },
            { id: 5, item: 'src/assets/head/head_06.png' },
            { id: 6, item: 'src/assets/head/head_07.png' },
            { id: 7, item: 'src/assets/head/head_08.png' },
            { id: 8, item: 'src/assets/head/head_09.png' },
            { id: 9, item: 'src/assets/head/head_10.png' },
            { id: 10, item: 'src/assets/head/head_11.png' },
            { id: 11, item: 'src/assets/head/head_12.png' },
            { id: 12, item: 'src/assets/head/head_13.png' },
            { id: 13, item: 'src/assets/head/head_14.png' },
            { id: 14, item: 'src/assets/head/head_15.png' },
            { id: 15, item: 'src/assets/head/head_16.png' },
            { id: 16, item: 'src/assets/head/head_17.png' },
            { id: 17, item: 'src/assets/head/head_18.png' },
            { id: 18, item: 'src/assets/head/head_19.png' },
            { id: 19, item: 'src/assets/head/head_20.png' },
            { id: 20, item: 'src/assets/head/head_21.png' },
            { id: 21, item: 'src/assets/head/head_22.png' },
        ],
    },
    exemples: [
        'src/assets/ex_01.png',
        'src/assets/ex_02.png',
        'src/assets/ex_03.png',
        'src/assets/ex_04.png',
        'src/assets/ex_05.png',
        'src/assets/ex_06.png',
    ]
}
